server:
  port: 8764

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: eureka-client-test #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8762   #匹配后提供服务的路由地址
          predicates:
            - Path=/client/test1/**   #断言,路径相匹配的进行路由

        - id: eureka-client-test2
          uri: http://localhost:8763
          predicates:
            - Path=/client/test2/**   #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
    #以IP地址注册到服务中心，相互注册使用IP地址
    preferIpAddress: true
    instance-id: 192.168.8.148:8764
  client:
    #eureka server注册中心的地址
    serviceUrl:
      defaultZone: http://192.168.8.148:8761/eureka/