server:
  port: 8764

spring:
  application:
    name: gateway
  cloud:
    gateway:
      #开启从注册中心动态获取路由的功能，利用微服务名进行路由；
      discovery.locator.enabled : true
      routes:
        - id: eureka-client-test #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8762   #匹配后提供服务的路由地址
          uri: lb://eureka-client-test #集群服务路由地址
          predicates: #predicates的多种配置方式可以参考：https://segmentfault.com/a/1190000019101829
            - Path=/client1/**   #断言,路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去掉Path前缀,参数为1代表去掉/ribbon

        - id: eureka-client-test
#          uri: http://localhost:8763
          uri: lb://eureka-client-test2 #集群服务路由地址
          predicates:
            - Path=/client2/**   #断言,路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去掉Path前缀,参数为1代表去掉/ribbon
eureka:
  instance:
    hostname: cloud-gateway-service
    #以IP地址注册到服务中心，相互注册使用IP地址
    preferIpAddress: true
    instance-id: 192.168.8.148:8764
  client:
    #eureka server注册中心的地址
    serviceUrl:
      defaultZone: http://192.168.8.148:8761/eureka/